apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage-testing

resources:
  - ../../base/redis

components:
 - ../../components/istio

patches:
  - patch: |
      - op: replace
        path: /spec/storageClassName
        value: nas-performance
    target:
      kind: PersistentVolumeClaim
      name: redis-follower-pvc
  - patch: |
      - op: replace
        path: /spec/storageClassName
        value: nas-performance
    target:
      kind: PersistentVolumeClaim
      name: redis-leader-pvc
