# Example yaml file for creation of persistent volumes manually
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basic-pvc
  namespace: storage-testing
  labels:
    app: no-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nas-standard
