apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- name: parameters
  env: params.env

replacements:
- source:
    kind: ConfigMap
    name: parameters
    fieldPath: data.clusterDomain
  targets:
  - select:
      kind: HTTPProxy
      name: wordpress
    fieldPaths:
    - spec.virtualhost.fqdn
    options:
      delimiter: '.'
      index: 1

resources:
 - frontend-httpproxy.yaml

generatorOptions:
  disableNameSuffixHash: true
