apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress

resources:
- namespace.yaml

commonLabels:
  cluster: dev-0.h2o-01-12345.h2o.vmware.com
  env: h2o-01-12345

generatorOptions:
  disableNameSuffixHash: true
