apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  cluster: dev-0.h2o-01-12345.h2o.vmware.com
  env: h2o-01-12345

patches:
- patch: |
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/storageClassName
      value: thin-disk
  target:
    kind: StatefulSet
    name: wordpress-mariadb

- patch: |
    - op: replace
      path: /spec/storageClassName
      value: thin-disk
  target:
    kind: PersistentVolumeClaim
    name: wordpress
