apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage-testing

resources:
- frontend-deployment.yaml
- frontend-service.yaml
- mongo-deployment.yaml
- mongo-service.yaml
- mongo-pvc.yaml
- mongo-client.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/gb-frontend:v5
  target:
    kind: Deployment
    name: frontend
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/mongo:4.2
  target:
    kind: Deployment
    name: mongo
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/mongo:4.2
  target:
    kind: Deployment
    name: mongo-client
