apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- ../../../base

patches:
- patch: |
    - op: replace
      path: /spec/storageClassName
      value: thin-disk
  target:
    kind: PersistentVolumeClaim
    name: data-wordpress-mariadb-0

- patch: |
    - op: replace
      path: /spec/storageClassName
      value: thin-disk
  target:
    kind: PersistentVolumeClaim
    name: wordpress
