apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/malston/kustomize-app-overlays/overlays/dev?ref=main

components:
- ../../components/ingress/contour
- ../../components/storage/thin-disk
