apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- name: parameters
  env: params.env

replacements:
- source:
    kind: ConfigMap
    name: parameters
    fieldPath: data.clusterDomain
  targets:
  - select:
      kind: VirtualService
      name: frontend
    fieldPaths:
    - spec.hosts.0
    options:
      delimiter: '.'
      index: 1

resources:
 - frontend-virtualservice.yaml

generatorOptions:
  disableNameSuffixHash: true
