apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

components:
- ../components/istio

patches:
- patch: |
    - op: replace
      path: /spec/storageClassName
      value: kubernetes-storage-policy
  target:
    kind: PersistentVolumeClaim
    name: wp-pv-claim
- patch: |
    - op: replace
      path: /spec/storageClassName
      value: kubernetes-storage-policy
  target:
    kind: PersistentVolumeClaim
    name: mysql-pv-claim
