apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testapp-wordpress

components:
- ../components/istio

resources:
- wordpress-namespace.yaml
- postgres-service.yaml
- wordpress-service.yaml
- postgres-statefulset.yaml
- wordpress-deployment.yaml
- wordpress-pvc.yaml

secretGenerator:
- name: postgres-secret
  literals:
  - password=password
generatorOptions:
  disableNameSuffixHash: true

patches:
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/postgres@sha256:3bfb87432e26badf72d727a0c5f5bb7b81438cd9baec5be8531c70a42b07adc6
  target:
    kind: StatefulSet
    name: wordpress-postgres

- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/wordpress@sha256:a27f4d25ae03950eb00b45859246a4a9a3c4999e083a78fac012dafe561f5628
  target:
    kind: Deployment
    name: wordpress
