apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-postgres
  labels:
    app: wordpress
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: postgres
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: wordpress
        tier: postgres
    spec:
      # securityContext:
      #   fsGroup: 999
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        livenessProbe:
          tcpSocket:
            port: 5432
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-pv-claim
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-pv-claim
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
