apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testapp-wordpress

resources:
- mysql-service.yaml
- wordpress-service.yaml
- mysql-deployment.yaml
- wordpress-deployment.yaml
- mysql-pvc.yaml
- wordpress-pvc.yaml

secretGenerator:
- name: mysql-pass
  literals:
  - password=password
generatorOptions:
  disableNameSuffixHash: true

patches:
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/mysql@sha256:d4c783e85ef8647a4350cb7aa7a8ddc7ebfd7cb217de4c2d1643e212ba94fcbd
  target:
    kind: Deployment
    name: wordpress-mysql
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/wordpress@sha256:ebbde622d13131d5dde0adb17a605b2a4885beddf2bf6f3c419dcb921dbc9f43
  target:
    kind: Deployment
    name: wordpress
