apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: wordpress
  includeCRDs: false
  valuesMerge: merge
  valuesInline:
    global:
      imageRegistry: harbor.markalston.net
      storageClass: kubernetes-storage-policy
    image:
      registry: harbor.markalston.net
      repository: test-apps/bitnami/wordpress
      tag: 6.4.3-debian-12-r18
      pullPolicy: Always
    persistence:
      storageClass: kubernetes-storage-policy
      size: 10Gi
    service:
      type: ClusterIP
    serviceAccount:
      create: false
    mariadb:
      serviceAccount:
        create: false
      image:
        repository: test-apps/bitnami/mariadb
        tag: 11.2.3-debian-12-r4
      networkPolicy:
        enabled: false
  releaseName: wordpress
  version: 20.0.1
  repo: https://charts.bitnami.com/bitnami

resources:
- ../../base

configMapGenerator:
- name: parameters
  env: params.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: parameters
    fieldPath: data.clusterDomain
  targets:
  - select:
      kind: VirtualService
      name: wordpress
    fieldPaths:
    - spec.hosts.0
    options:
      delimiter: '.'
      index: 1

components:
- ../../components/ingress/istio
- ../../components/storage/nas-performance
