apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: wordpress
  includeCRDs: false
  valuesMerge: merge
  valuesInline:
    global:
      imageRegistry: harbor.markalston.net
      storageClass: nas-performance
    image:
      registry: harbor.markalston.net
      repository: test-apps/bitnami/wordpress
      tag: 6.4.3-debian-12-r18
      pullPolicy: Always
    persistence:
      storageClass: nas-performance
      size: 10Gi
    service:
      type: ClusterIP
    serviceAccount:
      create: false
    mariadb:
      serviceAccount:
        create: false
      image:
        repository: test-apps/bitnami/mariadb
        tag: 11.2.3-debian-12-r4
      networkPolicy:
        enabled: false
  releaseName: wordpress
  version: 20.0.1
  repo: https://charts.bitnami.com/bitnami

replacements:
- source:
    fieldPath: metadata.labels.cluster
    kind: VirtualService
    name: wordpress
  targets:
  - select:
      kind: VirtualService
      name: wordpress
    fieldPaths:
    - spec.hosts.0
    options:
      delimiter: '.'
      index: 1

components:
- ../../components/ingress/istio
- ../../components/storage/nas-ultra

commonLabels:
  cluster: prod-0.h2o-75-23326.h2o.vmware.com
  env: h2o-75-23326
