apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ../../base/mongo

patches:
- patch: |
    - op: replace
      path: /spec/storageClassName
      value: nas-performance
  target:
    kind: PersistentVolumeClaim
    name: mongo-pvc
